version: "3.7"
services: 
# 数据库服务
  kong-database:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
    # 访问数据库的用户
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
    networks:
      - kong-net
    volumes:
    # 数据库持久化目录
      - ./docker-data/postgresql/postgresql:/var/lib/postgresql/data
networks:
  kong-net:
    external: true
